## Some global configuration stuff 

OCAMLFIND      := ocamlfind
OCAML          := ocaml
JS_OF_OCAML    := js_of_ocaml

ELIOMC         := eliomc
JS_OF_ELIOM    := js_of_eliom
ELIOMDEP       := eliomdep

OCLOSURE_REQ   := oclosure_req

ELIOMCLIENTDIR := $(shell ${OCAMLFIND} query eliom.client)
OCLOSUREDIR    := $(shell ${OCAMLFIND} query oclosure)

TEMP           := _build

STATICDIR      := ./public